version: '3'
services:
  mysql: 
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql  

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
    - 5672:5672 # (erlang) communication between the nodes and CLI tool
    - 15672:15672 # communication with the web management API 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
